### PR TITLE
Update release process and add floating tags

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Comment by sethvargo** [comment]
@bharathkkb

**Review by bharathkkb — APPROVED** [review]

**Comment by abdonrd** [comment]
I just get this error now:

> Error: Unable to resolve action `google-github-actions/deploy-appengine@v0`, unable to find version `v0`

**Comment by bharathkkb** [comment]
@abdonrd Could you open an issue? 

I do see the tag https://github.com/google-github-actions/deploy-appengine/tree/v0 so it looks like the workflow worked.

**Comment by abdonrd** [comment]
It seems that now it is working. False alarm!

**Pull request merged**
